title: AMDC Clustering Rendered Documents
description: Replicating results, figures and tables from 'Adjacency Matrix Decomposition Clustering for Human Activity Data' (https://arxiv.org/abs/2401.01949) by Martha Barnard, Yingling Fan, Julian Wolfson.
theme: jekyll-theme-cayman

